// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hajnqzqojsozuozmahnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhham5xenFvanNvenVvem1haG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NzkxODgsImV4cCI6MjA1MDU1NTE4OH0.tZuNsLVDOY7Yn79YPZ7nmQ6UUqOm4Go4E0_Pewlvrb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);